bases:
- https://github.com/bigkevmcd/taxi/deploy/templates
configMapGenerator:
- name: stage-www-files
  files:
  - index.html
  - staging.html
images:
- name: quay.io/kmcdermo/taxi
  newTag: 9aec91499279de97031d39189b579f100521e315
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: taxi
  path: staging_patch.yaml
