bases:
- https://github.com/bigkevmcd/taxi/deploy/templates
configMapGenerator:
- name: stage-www-files
  files:
  - index.html
  - staging.html
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: taxi
  path: staging_patch.yaml
